-- MySQL Script generated by MySQL Workbench
-- ter 30 nov 2021 10:51:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_user` (
  `idtb_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`idtb_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_topic` (
  `idtb_topic` INT NOT NULL AUTO_INCREMENT,
  `dearnews` VARCHAR(255) NULL,
  `socialworks` VARCHAR(255) NULL,
  `pets` VARCHAR(255) NULL,
  `personalreports` VARCHAR(255) NULL,
  PRIMARY KEY (`idtb_topic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_post` (
  `idtb_post` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `text` VARCHAR(1000) NULL,
  `image` VARCHAR(255) NULL,
  `datepost` DATE NULL,
  `tb_user_idtb_user` INT NOT NULL,
  `tb_topic_idtb_topic` INT NOT NULL,
  PRIMARY KEY (`idtb_post`, `tb_user_idtb_user`, `tb_topic_idtb_topic`),
  INDEX `fk_tb_post_tb_user1_idx` (`tb_user_idtb_user` ASC) VISIBLE,
  INDEX `fk_tb_post_tb_topic1_idx` (`tb_topic_idtb_topic` ASC) VISIBLE,
  CONSTRAINT `fk_tb_post_tb_user1`
    FOREIGN KEY (`tb_user_idtb_user`)
    REFERENCES `mydb`.`tb_user` (`idtb_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_post_tb_topic1`
    FOREIGN KEY (`tb_topic_idtb_topic`)
    REFERENCES `mydb`.`tb_topic` (`idtb_topic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
